name: Deploy to AWS ECS

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Build Docker image
        run: |
          docker build -t techtest-use .
          docker tag techtest-use:latest 014498643813.dkr.ecr.eu-west-2.amazonaws.com/techtest-use:latest

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image to ECR
        run: |
          docker push 014498643813.dkr.ecr.eu-west-2.amazonaws.com/techtest-use:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster techtest-use-cluster --service techtest-use-service --force-new-deployment --region eu-west-2
